apiVersion: v1
kind: Secret
metadata:
  name: {{ include "animus-datapilot.secretsName" . }}
  labels:
    {{- include "animus-datapilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  internalAuthSecret: {{ .Values.auth.internalAuthSecret | quote }}
  ciWebhookSecret: {{ .Values.ci.webhookSecret | quote }}
  databaseUrl: {{ include "animus-datapilot.databaseUrl" . | quote }}
  oidcClientSecret: {{ .Values.oidc.clientSecret | quote }}
  postgresPassword: {{ .Values.postgres.password | quote }}
  minioRootPassword: {{ .Values.minio.rootPassword | quote }}
  minioAccessKey: {{ .Values.minio.accessKey | quote }}
  minioSecretKey: {{ .Values.minio.secretKey | quote }}
